select
    nullif(trim(campaign_id), '') as campaign_id,
    nullif(trim(campaign_name), '') as campaign_name,
    nullif(trim(campaign_type), '') as campaign_type,
    nullif(trim(promo_code), '') as promo_code,
    discount_percent,
    discount_amount,
    nullif(trim(discount_rules), '') as discount_rules,
    start_date,
    end_date,
    min_order_amount,
    max_uses_per_customer,
    total_uses,
    budget,
    actual_spend,
    nullif(trim(target_spend), '') as target_spend,
    nullif(trim(campaign_channel), '') as campaign_channel,
    nullif(trim(campaign_status), '') as campaign_status,
    nullif(trim(created_by), '') as created_by,
    created_at,
    updated_at,
    load_timestamp,
    source_file
from {{ source('bronze', 'bronze_promo_campaigns') }}
where campaign_id is not null
